// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stefan_Jesenko_LBM295API.Models;

#nullable disable

namespace Stefan_Jesenko_LBM295API.Migrations
{
    [DbContext(typeof(PizzaDB))]
    [Migration("20240205093441_PizzaDbErstellt")]
    partial class PizzaDbErstellt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaZutaten", b =>
                {
                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("ZutatensId")
                        .HasColumnType("int");

                    b.HasKey("PizzaId", "ZutatensId");

                    b.HasIndex("ZutatensId");

                    b.ToTable("PizzaZutaten");
                });

            modelBuilder.Entity("Stefan_Jesenko_LBM295API.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PizzaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzen");
                });

            modelBuilder.Entity("Stefan_Jesenko_LBM295API.Models.Zutaten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Zutat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zutaten");
                });

            modelBuilder.Entity("PizzaZutaten", b =>
                {
                    b.HasOne("Stefan_Jesenko_LBM295API.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stefan_Jesenko_LBM295API.Models.Zutaten", null)
                        .WithMany()
                        .HasForeignKey("ZutatensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
